name: Magma AGW Build Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'v1.6.1'
      environment:
        description: 'dev - test - release'
        required: true
        default: 'dev'

jobs:
  Magma-AGW-Build-Version:
    runs-on: macos-10.15
    env:
      ID_RSA: ${{ secrets.ID_RSA }}
      ID_PUB: ${{ secrets.ID_PUB }}
    steps:
    - run: echo "::set-output name=date::$(date +'%m-%d-%Y--%H-%M-%S')"
      id: date
    - uses: actions/checkout@v2
    - run: ./build-version.sh ${{ github.event.inputs.version }} ${{ github.event.inputs.environment }}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.date.outputs.date }}
        prerelease: false
        files: |
          magma/lte/gateway/magma-packages/*.deb
    - uses: actions/upload-artifact@v2
      with:
        name: magma-packages
        path: magma/lte/gateway/magma-packages/*.deb
